%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(order).
-define(order, true).

-define(order_gpb_version, "4.1.1").

-ifndef('ORDER_PB_H').
-define('ORDER_PB_H', true).
-record('Order',
        {confirmation = false   :: boolean() | 0 | 1, % = 1
         type = false           :: boolean() | 0 | 1, % = 2
         symbol = <<>>          :: iodata(),        % = 3
         quantity = 0           :: integer(),       % = 4, 32 bits
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan, % = 5
         user = <<>>            :: iodata()         % = 6
        }).
-endif.

-endif.
