%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(order).
-define(order, true).

-define(order_gpb_version, "4.1.1").

-ifndef('ORDER_PB_H').
-define('ORDER_PB_H', true).
-record('Order',
        {quantity = 0           :: integer() | undefined, % = 1, 32 bits
         price = 0.0            :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 2
         user = <<>>            :: iodata() | undefined, % = 3
         symbol = <<>>          :: iodata() | undefined, % = 4
         orderType = false      :: boolean() | 0 | 1 | undefined % = 5
        }).
-endif.

-endif.
