%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(order).
-define(order, true).

-define(order_gpb_version, "4.1.1").

-ifndef('ORDER_PB_H').
-define('ORDER_PB_H', true).
-record('Order',
        {orderType              :: 'BUY' | 'SELL' | integer(), % = 0, enum Order.Type
         symbol                 :: iodata(),        % = 1
         quantity               :: integer(),       % = 2, 32 bits
         price                  :: float() | integer() | infinity | '-infinity' | nan, % = 3
         user                   :: iodata()         % = 4
        }).
-endif.

-endif.
