%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(response).
-define(response, true).

-define(response_gpb_version, "4.1.1").

-ifndef('RESPONSE_PB_H').
-define('RESPONSE_PB_H', true).
-record('Response',
        {rep                    :: boolean() | 0 | 1 % = 1
        }).
-endif.

-endif.
