%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(update).
-define(update, true).

-define(update_gpb_version, "4.1.1").

-ifndef('UPDATE_PB_H').
-define('UPDATE_PB_H', true).
-record('Update',
        {user = <<>>            :: iodata() | undefined % = 1
        }).
-endif.

-endif.
